# Script to convert casacore images generated by the AARTFAAC pipeline to FITS.
# pep/10Jun12

import glob;
import os;

print 'Generating FITS files from integrating all subband images in current folder';
default (exportfits)
 
# for image_file in glob.glob(os.path.join('fits/','*.fits')):
sb4 = glob.glob ('60537719/*.image');
sb3 = glob.glob ('60342407/*.image');
sb2 = glob.glob ('60147094/*.image');        
sb1 = glob.glob ('59951782/*.image');
sb0 = glob.glob ('59756469/*.image');
usable_files = min(len(sb1), len(sb2), len (sb3), len(sb4));
print 'Found ', usable_files, ' common files';
os.system ('mkdir 2subband_diff/');
for ind in range (1, min (len(sb0), len(sb1))):
	m = re.search ('_(.+?).image', sb1[ind]);
	outfile = '2subband_diff/casacore'+m.group(1)+'.image';
	imagename = [sb0[ind], sb1[ind], sb2[ind], sb3[ind]]
	mode = 'evalexpr';
#	expr = '(IM0 - IM1 - IM2 - IM3 )';
	expr = '(IM0 - IM1 )';
	print 'Differencing', sb0[ind], ' ', sb1[ind],' ', sb2[ind],' ', sb3[ind];
	immath ();
	print 'Done';
	print 'Exporting to fits'
	imagename = outfile;
	fitsimage = '2subband_diff/5sb_'+m.group(1)+ '.image.fits';
	exportfits ();
	print 'Done';

